// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenSkiTime.Persistence;

#nullable disable

namespace OpenSkiTime.Persistence.Migrations
{
    [DbContext(typeof(OpenSkiTimeDbContext))]
    [Migration("20260528162742_0002_Competitors_Participation_Categories")]
    partial class _0002_Competitors_Participation_Categories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("OpenSkiTime.Domain.CategoryRules.CategoryRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BirthYearMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthYearMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EventSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventSeriesId");

                    b.ToTable("CategoryRules", (string)null);
                });

            modelBuilder.Entity("OpenSkiTime.Domain.Competitions.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Discipline")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EventSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinishAltitudeMeters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FisCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomologationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalRaceCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfIntermediateTimes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfRuns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartAltitudeMeters")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VerticalDropMeters")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventSeriesId", "Date")
                        .HasDatabaseName("IX_Competitions_EventSeriesId_Date");

                    b.HasIndex("EventSeriesId", "ShortLabel")
                        .IsUnique()
                        .HasDatabaseName("UQ_Competitions_EventSeriesId_ShortLabel");

                    b.ToTable("Competitions", (string)null);
                });

            modelBuilder.Entity("OpenSkiTime.Domain.Competitors.Competitor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BibNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClubName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FisCode")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName");

                    b.Property<string>("NationCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventSeriesId");

                    b.ToTable("Competitors", (string)null);
                });

            modelBuilder.Entity("OpenSkiTime.Domain.Participation.Participation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompetitorId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsParticipating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorId", "CompetitionId")
                        .IsUnique();

                    b.ToTable("Participations", (string)null);
                });

            modelBuilder.Entity("OpenSkiTime.Domain.Series.EventSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("RowVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EventSeries", (string)null);
                });

            modelBuilder.Entity("OpenSkiTime.Domain.CategoryRules.CategoryRule", b =>
                {
                    b.HasOne("OpenSkiTime.Domain.Series.EventSeries", null)
                        .WithMany("CategoryRules")
                        .HasForeignKey("EventSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Domain.Competitions.Competition", b =>
                {
                    b.HasOne("OpenSkiTime.Domain.Series.EventSeries", null)
                        .WithMany("Competitions")
                        .HasForeignKey("EventSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Domain.Competitors.Competitor", b =>
                {
                    b.HasOne("OpenSkiTime.Domain.Series.EventSeries", null)
                        .WithMany("Competitors")
                        .HasForeignKey("EventSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Domain.Participation.Participation", b =>
                {
                    b.HasOne("OpenSkiTime.Domain.Competitors.Competitor", null)
                        .WithMany("Participations")
                        .HasForeignKey("CompetitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Domain.Competitors.Competitor", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("OpenSkiTime.Domain.Series.EventSeries", b =>
                {
                    b.Navigation("CategoryRules");

                    b.Navigation("Competitions");

                    b.Navigation("Competitors");
                });
#pragma warning restore 612, 618
        }
    }
}
