// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenSkiTime.Rewrite.Persistence;

#nullable disable

namespace OpenSkiTime.Rewrite.Persistence.Migrations
{
    [DbContext(typeof(SeriesDbContext))]
    [Migration("20260926121406_Competitions")]
    partial class Competitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.CompetitionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinishAltitudeMeters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FisCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomologationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("IntermediateCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalRaceCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("RunCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortLabelKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartAltitudeMeters")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VerticalDropMeters")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "ShortLabelKey")
                        .IsUnique();

                    b.ToTable("Competitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Competition_Intermediates", "IntermediateCount BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Competition_Runs", "RunCount BETWEEN 1 AND 9");
                        });
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.SeriesRow", b =>
                {
                    b.Property<int>("SingleRow")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormatId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SingleRow");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Series", null, t =>
                        {
                            t.HasCheckConstraint("CK_Series_Format", "FormatId = 'OpenSkiTime.New/1'");

                            t.HasCheckConstraint("CK_Series_OneRow", "SingleRow = 1");
                        });
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.CompetitionRow", b =>
                {
                    b.HasOne("OpenSkiTime.Rewrite.Persistence.SeriesRow", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
