// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenSkiTime.Rewrite.Persistence;

#nullable disable

namespace OpenSkiTime.Rewrite.Persistence.Migrations
{
    [DbContext(typeof(SeriesDbContext))]
    partial class SeriesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.CaptureRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CleanStop")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ListId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("TimingCaptures", (string)null);
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.CategoryRuleRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BirthYearMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthYearMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "LabelKey")
                        .IsUnique();

                    b.ToTable("CategoryRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_Category_Years", "BirthYearMin >= 1850 AND BirthYearMin <= BirthYearMax");
                        });
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.CompetitionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinishAltitudeMeters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FisCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomologationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("IntermediateCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalRaceCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("RunCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortLabelKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartAltitudeMeters")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VerticalDropMeters")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "ShortLabelKey")
                        .IsUnique();

                    b.ToTable("Competitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Competition_Intermediates", "IntermediateCount BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Competition_Runs", "RunCount BETWEEN 1 AND 9");
                        });
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.CompetitorRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Club")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("FederationCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FederationCodeKey")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nation")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "FederationCodeKey")
                        .IsUnique();

                    b.ToTable("Competitors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Competitor_BirthYear", "BirthYear IS NULL OR BirthYear >= 1850");
                        });
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.ImportReceiptRow", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Updated")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeriesId", "SourceHash");

                    b.ToTable("ImportReceipts", (string)null);
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.ParticipationRow", b =>
                {
                    b.Property<Guid>("CompetitorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportedBib")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Participates")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompetitorId", "CompetitionId");

                    b.HasIndex("SeriesId", "CompetitorId");

                    b.HasIndex("SeriesId", "CompetitionId", "ImportedBib")
                        .IsUnique();

                    b.ToTable("Participations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Participation_Bib", "ImportedBib IS NULL OR ImportedBib BETWEEN 1 AND 99999");
                        });
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.RawPacketRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stream")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "Sequence");

                    b.ToTable("RawTimingPackets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Raw_Sequence", "Sequence > 0");
                        });
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.RunRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "Gender", "Number")
                        .IsUnique();

                    b.ToTable("Runs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Run_Number", "Number BETWEEN 1 AND 9");
                        });
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.SeriesRow", b =>
                {
                    b.Property<int>("SingleRow")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormatId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SingleRow");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Series", null, t =>
                        {
                            t.HasCheckConstraint("CK_Series_Format", "FormatId = 'OpenSkiTime.New/1'");

                            t.HasCheckConstraint("CK_Series_OneRow", "SingleRow = 1");
                        });
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.StartListEntryRow", b =>
                {
                    b.Property<Guid>("ListId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bib")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CompetitorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ListId", "Position");

                    b.HasIndex("ListId", "Bib")
                        .IsUnique();

                    b.HasIndex("ListId", "CompetitorId")
                        .IsUnique();

                    b.ToTable("StartListEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_Start_Bib", "Bib BETWEEN 1 AND 99999");

                            t.HasCheckConstraint("CK_Start_Position", "Position > 0");
                        });
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.StartListRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTimingVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Revision")
                        .IsUnique();

                    b.ToTable("StartLists", (string)null);
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.TimingAuditRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReversesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ListId", "Id");

                    b.ToTable("TimingAudit", (string)null);
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.CaptureRow", b =>
                {
                    b.HasOne("OpenSkiTime.Rewrite.Persistence.StartListRow", null)
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.CategoryRuleRow", b =>
                {
                    b.HasOne("OpenSkiTime.Rewrite.Persistence.SeriesRow", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.CompetitionRow", b =>
                {
                    b.HasOne("OpenSkiTime.Rewrite.Persistence.SeriesRow", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.CompetitorRow", b =>
                {
                    b.HasOne("OpenSkiTime.Rewrite.Persistence.SeriesRow", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.ImportReceiptRow", b =>
                {
                    b.HasOne("OpenSkiTime.Rewrite.Persistence.SeriesRow", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.ParticipationRow", b =>
                {
                    b.HasOne("OpenSkiTime.Rewrite.Persistence.CompetitionRow", null)
                        .WithMany()
                        .HasForeignKey("SeriesId", "CompetitionId")
                        .HasPrincipalKey("SeriesId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenSkiTime.Rewrite.Persistence.CompetitorRow", null)
                        .WithMany()
                        .HasForeignKey("SeriesId", "CompetitorId")
                        .HasPrincipalKey("SeriesId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.RawPacketRow", b =>
                {
                    b.HasOne("OpenSkiTime.Rewrite.Persistence.CaptureRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.RunRow", b =>
                {
                    b.HasOne("OpenSkiTime.Rewrite.Persistence.CompetitionRow", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.StartListEntryRow", b =>
                {
                    b.HasOne("OpenSkiTime.Rewrite.Persistence.StartListRow", null)
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.StartListRow", b =>
                {
                    b.HasOne("OpenSkiTime.Rewrite.Persistence.RunRow", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenSkiTime.Rewrite.Persistence.TimingAuditRow", b =>
                {
                    b.HasOne("OpenSkiTime.Rewrite.Persistence.StartListRow", null)
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
