<Project>
  <Target Name="CopyLiveTimingProcesses" AfterTargets="Build">
    <ItemGroup>
      <LiveWorkerFiles Include="$(MSBuildThisFileDirectory)src/OpenSkiTime.LiveTiming.Worker/bin/$(Configuration)/$(TargetFramework)/**/*" />
      <LiveServerFiles Include="$(MSBuildThisFileDirectory)src/OpenSkiTime.LiveTiming.Server/bin/$(Configuration)/$(TargetFramework)/**/*" />
    </ItemGroup>
    <Copy SourceFiles="@(LiveWorkerFiles)" DestinationFiles="@(LiveWorkerFiles->'$(OutDir)LiveTiming/Worker/%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(LiveServerFiles)" DestinationFiles="@(LiveServerFiles->'$(OutDir)LiveTiming/Server/%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
  <Target Name="PublishLiveTimingProcesses" AfterTargets="Publish" DependsOnTargets="CopyLiveTimingProcesses">
    <Copy SourceFiles="@(LiveWorkerFiles)" DestinationFiles="@(LiveWorkerFiles->'$(PublishDir)LiveTiming/Worker/%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(LiveServerFiles)" DestinationFiles="@(LiveServerFiles->'$(PublishDir)LiveTiming/Server/%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
