<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <ProjectReference Include="../OpenSkiTime.Rewrite.Application/OpenSkiTime.Rewrite.Application.csproj" />
  </ItemGroup>
</Project>
